apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-npkn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-npkn@sha256:2b27c4a04e718aa22c1090c374bfb8e2754adfd432c59dcbc68fd87173250f7f
        name: my-nodejs
        resources: {}
status: {}
